version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "python", "scripts/health_check.py"]
      interval: 30s

  db:
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:alpine

volumes:
  pg_data:

  # Веб API сервер
  web-api:
    build:
      context: ..
      dockerfile: Dockerfile.web
    container_name: ai-pipeline-web
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - redis
      - db
    restart: unless-stopped
    networks:
      - ai-pipeline-network
